<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-45NSA3K4" failures="1" tests="3" name="StandAloneTest" time="32.968" errors="0" timestamp="17 Nov 2024 16:59:02 GMT">
  <testcase classname="E2EPractiseProject.StandAloneTest" name="submitOrder" time="17.604"/>
  <testcase classname="E2EPractiseProject.StandAloneTest" name="submitOrder" time="9.982">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at E2EPractiseProject.StandAloneTest.submitOrder(StandAloneTest.java:43)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="E2EPractiseProject.StandAloneTest" name="orderHistoryTest" time="0.0">
    <skipped/>
  </testcase> <!-- orderHistoryTest -->
</testsuite> <!-- StandAloneTest -->
